const canvas=document.getElementById('world'),ctx=canvas.getContext('2d');
let W,H,dpr,world='bubbles',t=0,items=[],ws,intensity=.7,speed=1,hue=205,held=new Set();
const TAU=Math.PI*2, rnd=(a,b)=>a+Math.random()*(b-a), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function resize(){dpr=Math.min(devicePixelRatio||1,1.5);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener('resize',resize);resize();
function bubble(x=rnd(0,W),y=H+30,r=rnd(12,45),c='80,170,255'){items.push({kind:'bubble',x,y,r,vx:rnd(-.45,.45),vy:rnd(-.35,-1.05),c,w:rnd(0,TAU)})}
function ripple(x=W/2,y=H/2,p=1,c='80,180,255'){items.push({kind:'ripple',x,y,r:5,p,life:1,c})}
function spark(x=W/2,y=H/2,c='255,220,100'){items.push({kind:'spark',x,y,vx:rnd(-4,4),vy:rnd(-4,4),life:1,c})}
function bolt(power=1){let pts=[],tx=rnd(W*.2,W*.8),start=rnd(W*.15,W*.85);for(let i=0;i<24;i++){let q=i/23;pts.push({x:start+(tx-start)*q+rnd(-45,45)*(1-q),y:q*H*.82})}items.push({kind:'bolt',pts,life:1,power})}
function action(n,down=true){
 const key=['','BLUE','RED','GREEN','YELLOW'][n]; down?held.add(key):held.delete(key); if(!down)return;
 if(world==='bubbles'){if(n===1)for(let i=0;i<3;i++)bubble(rnd(W*.15,W*.85),H+20,rnd(25,65));if(n===2){ripple(W/2,H/2,3,'255,70,90');items.forEach(o=>{if(o.kind==='bubble'){o.vx+=(o.x-W/2)*.004;o.vy-=.8}})}if(n===3)for(let i=0;i<9;i++)bubble(rnd(W*.38,W*.62),H-20,rnd(8,26),'40,230,130');if(n===4)for(let i=0;i<18;i++)spark(rnd(W*.3,W*.7),rnd(H*.25,H*.7),'255,215,80')}
 else if(world==='waves'){if(n===1)ripple(rnd(W*.15,W*.85),rnd(H*.2,H*.75),1.2);if(n===2)for(let i=0;i<3;i++)ripple(W/2,H/2,2.5+i*.5,'255,100,130');if(n===3)for(let i=0;i<12;i++)ripple(rnd(0,W),rnd(0,H),.6,'80,240,180');if(n===4)for(let i=0;i<16;i++)spark(rnd(0,W),rnd(H*.15,H*.8),'255,230,110')}
 else if(world==='electricity'){if(n===1)bolt(1);if(n===2)for(let i=0;i<5;i++)bolt(1.4);if(n===3)for(let i=0;i<3;i++)bolt(.7);if(n===4)for(let i=0;i<35;i++)spark(W/2,H/2,'180,220,255')}
 else {if(n===1)items.push({kind:'orb',x:rnd(W*.2,W*.8),y:rnd(H*.2,H*.8),r:10,life:1,h:hue});if(n===2)hue=(hue+180)%360;if(n===3)for(let i=0;i<12;i++)items.push({kind:'orb',x:rnd(0,W),y:rnd(0,H),r:rnd(8,28),life:1,h:(hue+i*12)%360});if(n===4)for(let i=0;i<24;i++)spark(rnd(0,W),rnd(0,H),'255,255,255')}
}
for(let i=1;i<=4;i++){const el=document.getElementById(['blue','red','green','yellow'][i-1]);el.onpointerdown=()=>action(i,true);el.onpointerup=()=>action(i,false)}
const worlds=['bubbles','waves','electricity','hue'];
function nextWorld(){setWorld(worlds[(worlds.indexOf(world)+1)%worlds.length])}
addEventListener('keydown',e=>{if('1234'.includes(e.key))action(+e.key,true);if(e.key.toLowerCase()==='m')nextWorld()});
addEventListener('keyup',e=>{if('1234'.includes(e.key))action(+e.key,false)});
function setWorld(w){if(!worlds.includes(w))w='bubbles';world=w;items=[];document.getElementById('modeName').textContent=(w==='hue'?'HUE':w.toUpperCase())+' WORLD';report()}
document.getElementById('modeButton').onclick=nextWorld;
function background(){
 if(world==='bubbles'){let g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,'#020817');g.addColorStop(.45,'#062b49');g.addColorStop(1,'#031525');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<8;i++){let x=(i*173+t*18)% (W+240)-120,y=H*(.15+.1*(i%6));let rg=ctx.createRadialGradient(x,y,0,x,y,180);rg.addColorStop(0,'rgba(60,190,255,.08)');rg.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=rg;ctx.fillRect(x-180,y-180,360,360)}}
 else if(world==='waves'){let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#063b57');g.addColorStop(.55,'#07506a');g.addColorStop(1,'#021e32');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let layer=0;layer<3;layer++){ctx.strokeStyle=`rgba(${100+layer*35},${205+layer*12},255,${.08+.06*intensity})`;ctx.lineWidth=1+layer*.5;for(let y=15+layer*12;y<H;y+=48){ctx.beginPath();for(let x=0;x<=W;x+=18){let yy=y+Math.sin(x*.014+t*(1.2+layer*.3)+y*.018)* (8+layer*4)*intensity;x?ctx.lineTo(x,yy):ctx.moveTo(x,yy)}ctx.stroke()}}}
 else if(world==='electricity'){let g=ctx.createRadialGradient(W*.5,H*.45,0,W*.5,H*.45,Math.max(W,H)*.7);g.addColorStop(0,'#101a3b');g.addColorStop(.45,'#080c22');g.addColorStop(1,'#02030a');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<45;i++){let x=(i*137)%W,y=(i*79+t*(6+i%5))%H;ctx.fillStyle=`rgba(130,170,255,${.08+(i%4)*.025})`;ctx.fillRect(x,y,1.5,1.5)}}
 else {hue=(hue+.08*speed)%360;let g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,`hsl(${hue},75%,28%)`);g.addColorStop(.5,`hsl(${(hue+65)%360},80%,42%)`);g.addColorStop(1,`hsl(${(hue+135)%360},72%,25%)`);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<6;i++){let x=W*(.15+.14*i)+Math.sin(t*.35+i)*W*.08,y=H*(.25+.1*(i%4))+Math.cos(t*.28+i)*H*.12;let rg=ctx.createRadialGradient(x,y,0,x,y,Math.min(W,H)*.32);rg.addColorStop(0,`hsla(${(hue+i*35)%360},95%,70%,.16)`);rg.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=rg;ctx.fillRect(x-W*.3,y-H*.3,W*.6,H*.6)}}
}
function drawItem(o,i){
 if(o.kind==='bubble'){o.w+=.015;o.x+=o.vx*speed+Math.sin(o.w)*.12;o.y+=o.vy*speed;if(o.y<-o.r){items.splice(i,1);return}let g=ctx.createRadialGradient(o.x-o.r*.32,o.y-o.r*.35,1,o.x,o.y,o.r);g.addColorStop(0,'rgba(255,255,255,.9)');g.addColorStop(.16,`rgba(${o.c},${.25+.45*intensity})`);g.addColorStop(.72,`rgba(${o.c},.10)`);g.addColorStop(1,'rgba(255,255,255,.28)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(o.x,o.y,o.r,0,TAU);ctx.fill();ctx.strokeStyle='rgba(210,245,255,.38)';ctx.lineWidth=1;ctx.stroke();ctx.beginPath();ctx.arc(o.x-o.r*.25,o.y-o.r*.3,o.r*.2,Math.PI,Math.PI*1.7);ctx.strokeStyle='rgba(255,255,255,.7)';ctx.stroke()}
 else if(o.kind==='ripple'){o.r+=4.2*speed;o.life-=.008*speed;if(o.life<=0){items.splice(i,1);return}for(let k=0;k<2;k++){ctx.strokeStyle=`rgba(${o.c},${o.life*(.42-k*.12)*intensity})`;ctx.lineWidth=1+o.p*2-k*.5;ctx.beginPath();ctx.ellipse(o.x,o.y,o.r-k*7,o.r*.42-k*3,0,0,TAU);ctx.stroke()}}
 else if(o.kind==='bolt'){o.life-=.045*speed;if(o.life<=0){items.splice(i,1);return}ctx.save();ctx.shadowBlur=12;ctx.shadowColor='rgba(120,180,255,.8)';ctx.beginPath();o.pts.forEach((p,j)=>j?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.strokeStyle=`rgba(205,230,255,${o.life*intensity})`;ctx.lineWidth=1.5+o.power*2.5;ctx.stroke();ctx.restore();if(Math.random()<.35)for(let k=0;k<2;k++){let p=o.pts[Math.floor(rnd(5,o.pts.length-3))];spark(p.x,p.y,'150,200,255')}}
 else if(o.kind==='orb'){o.r+=2;o.life-=.012;if(o.life<=0){items.splice(i,1);return}let g=ctx.createRadialGradient(o.x,o.y,0,o.x,o.y,o.r*2);g.addColorStop(0,`hsla(${o.h},100%,80%,${o.life*.7})`);g.addColorStop(1,`hsla(${o.h},100%,50%,0)`);ctx.fillStyle=g;ctx.beginPath();ctx.arc(o.x,o.y,o.r*2,0,TAU);ctx.fill()}
 else{o.x+=o.vx*speed;o.y+=o.vy*speed;o.vx*=.985;o.vy*=.985;o.life-=.025*speed;if(o.life<=0){items.splice(i,1);return}ctx.globalAlpha=o.life;ctx.fillStyle=`rgb(${o.c})`;ctx.beginPath();ctx.arc(o.x,o.y,1.5+2*o.life,0,TAU);ctx.fill();ctx.globalAlpha=1}
}
function draw(){t+=.016*speed;background();if(world==='bubbles'&&items.filter(x=>x.kind==='bubble').length<18)bubble(rnd(0,W),H+30,rnd(8,34));if(world==='electricity'&&Math.random()<.008*intensity)bolt(.45);if(world==='hue'&&Math.random()<.015*intensity)items.push({kind:'orb',x:rnd(0,W),y:rnd(0,H),r:5,life:.7,h:(hue+rnd(-50,50)+360)%360});for(let i=items.length-1;i>=0;i--)drawItem(items[i],i);requestAnimationFrame(draw)}
function remoteInput(event){const m={BLUE_DOWN:1,RED_DOWN:2,GREEN_DOWN:3,YELLOW_DOWN:4,BLUE_UP:1,RED_UP:2,GREEN_UP:3,YELLOW_UP:4};if(m[event])action(m[event],event.endsWith('_DOWN'))}
function connect(){ws=new WebSocket(`ws://${location.host}/ws?role=display`);ws.onopen=report;ws.onclose=()=>setTimeout(connect,1500);ws.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m.type==='command'&&m.command==='reload'){window.location.replace('/index.html?reload='+Date.now());return}if(m.type==='input'&&m.event)remoteInput(m.event);if((m.type==='state'||m.type==='hello')&&m.state){let s=m.state;if(s.world&&s.world!==world)setWorld(s.world);intensity=(s.intensity??70)/100;speed=(s.speed??100)/100;document.getElementById('controls').style.display=s.showControls===false?'none':'flex'}}}
function report(){if(ws?.readyState===1)ws.send(JSON.stringify({type:'screen_state',version:'v0.7',world}))}
connect();draw();
