const canvas=document.getElementById('world'),ctx=canvas.getContext('2d');
let W,H,dpr,world='bubbles',t=0,items=[],balls=[],ws,intensity=.7,speed=1,hue=205,held=new Set();
let control={knob:50,roller:0,jx:0,jy:0},fps=30,quality='HIGH',lastFrame=performance.now(),fpsClock=lastFrame,fpsFrames=0,lastReport=0,physicsAcc=0,lastPaint=performance.now()-40,physicsMs=0,renderMs=0,frameMs=0,maxFrameMs=0,lateFrames=0;
const TARGET_MS=1000/30,ballSprites=new Map(),bubbleSprites=new Map();
const TAU=Math.PI*2,rnd=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function resize(){dpr=1;W=innerWidth;H=innerHeight;canvas.width=W;canvas.height=H;canvas.style.width='';canvas.style.height='';ctx.setTransform(1,0,0,1,0,0);balls.forEach(b=>{b.x=clamp(b.x,b.r,W-b.r);b.y=clamp(b.y,b.r,H-b.r)})}
addEventListener('resize',resize);resize();
function bubble(x=rnd(0,W),y=H+30,r=rnd(12,45),c='80,170,255'){if(items.length<140)items.push({kind:'bubble',x,y,r,vx:rnd(-.65,.65),vy:rnd(-.8,-2.35),c,w:rnd(0,TAU),phase:rnd(0,TAU),depth:rnd(.65,1.15),rise:rnd(.8,1.65),age:0,maxAge:rnd(4.5,10)})}
function bubbleSprite(c){const hit=bubbleSprites.get(c);if(hit)return hit;const s=document.createElement('canvas');s.width=s.height=128;const x=s.getContext('2d'),g=x.createRadialGradient(46,39,3,64,64,57);g.addColorStop(0,'rgba(255,255,255,.92)');g.addColorStop(.09,'rgba('+c+',.30)');g.addColorStop(.58,'rgba('+c+',.08)');g.addColorStop(.84,'rgba(255,255,255,.05)');g.addColorStop(1,'rgba(210,245,255,.46)');x.fillStyle=g;x.beginPath();x.arc(64,64,57,0,TAU);x.fill();x.strokeStyle='rgba(220,250,255,.48)';x.lineWidth=2;x.stroke();x.strokeStyle='rgba(255,255,255,.62)';x.lineWidth=4;x.beginPath();x.arc(50,47,30,3.55,4.9);x.stroke();x.fillStyle='rgba(255,255,255,.65)';x.beginPath();x.arc(43,39,5,0,TAU);x.fill();bubbleSprites.set(c,s);return s}
function bubbleBurst(x,y,c){ripple(x,y,1.2,c);for(let i=0;i<8;i++){let a=i/8*TAU+rnd(-.18,.18),v=rnd(1.2,3);if(items.length<140)items.push({kind:'spark',x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:rnd(.45,.8),c})}}
function ripple(x=W/2,y=H/2,p=1,c='80,180,255'){if(items.length<140)items.push({kind:'ripple',x,y,r:5,p,life:1,c})}
function spark(x=W/2,y=H/2,c='255,220,100'){if(items.length<140)items.push({kind:'spark',x,y,vx:rnd(-4,4),vy:rnd(-4,4),life:1,c})}
function bolt(power=1){if(items.length>=120)return;let pts=[],tx=rnd(W*.2,W*.8),start=rnd(W*.15,W*.85);for(let i=0;i<20;i++){let q=i/19;pts.push({x:start+(tx-start)*q+rnd(-42,42)*(1-q),y:q*H*.82})}items.push({kind:'bolt',pts,life:1,power})}
const ballColors=['#48a8ff','#ff5f72','#42d88a','#ffd34e','#b878ff','#ff8f4c','#4fe1dd'];
function ballSprite(c){if(ballSprites.has(c))return ballSprites.get(c);const s=document.createElement('canvas');s.width=s.height=112;const x=s.getContext('2d'),g=x.createRadialGradient(40,36,2,56,56,50);g.addColorStop(0,'#fff');g.addColorStop(.13,c);g.addColorStop(1,'#172033');x.fillStyle=g;x.beginPath();x.arc(56,56,50,0,TAU);x.fill();x.strokeStyle='rgba(255,255,255,.3)';x.lineWidth=2;x.stroke();ballSprites.set(c,s);return s}
function addBall(x=rnd(W*.15,W*.85),y=rnd(H*.08,H*.35),r=14+control.knob*.32){if(balls.length>=40)return;balls.push({x,y,r:clamp(r,14,48),vx:rnd(-90,90),vy:rnd(-30,60),c:ballColors[balls.length%ballColors.length]})}
function resetPhysics(){balls=[];for(let i=0;i<16;i++)addBall(rnd(W*.15,W*.85),rnd(H*.08,H*.65),rnd(17,34))}
function physicsPulse(){for(const b of balls){let dx=b.x-W/2,dy=b.y-H/2,d=Math.hypot(dx,dy)||1,f=460/(1+d*.002);b.vx+=dx/d*f;b.vy+=dy/d*f}ripple(W/2,H/2,4,'255,110,120')}
function action(n,down=true){const key=['','BLUE','RED','GREEN','YELLOW'][n];down?held.add(key):held.delete(key);if(!down)return;
 if(world==='physics'){if(n===1)for(let i=0;i<3;i++)addBall(W/2+rnd(-80,80),60);if(n===2)physicsPulse();if(n===3)control.jy=clamp(control.jy+.25,-1,1);if(n===4)control.jy=clamp(control.jy-.25,-1,1);return}
 if(world==='bubbles'){if(n===1){for(let i=0;i<12;i++){let a=rnd(-1.05,-.52),v=rnd(1.4,3.4),size=rnd(12,30)+control.knob*.18;bubble(W/2+rnd(-55,55),H+rnd(0,35),size,'55,175,255');let o=items[items.length-1];o.vx=Math.cos(a)*v*1.55;o.vy=Math.sin(a)*v*1.55}}if(n===2){items.push({kind:'popwave',x:W/2,y:H*.5,r:10,life:1,c:'255,85,120'});ripple(W/2,H*.5,5,'255,85,120')}if(n===3){for(let i=0;i<24;i++)bubble(rnd(W*.12,W*.88),H+rnd(0,70),rnd(7,20),'45,235,165')}if(n===4){items.push({kind:'mega',x:W/2,y:H*.53,r:25,target:Math.min(W,H)*.24,life:1,c:'255,205,55'})}}
 else if(world==='waves'){if(n===1)ripple(rnd(W*.15,W*.85),rnd(H*.2,H*.75),1.2);if(n===2)for(let i=0;i<3;i++)ripple(W/2,H/2,2.5+i*.5,'255,100,130');if(n===3)for(let i=0;i<12;i++)ripple(rnd(0,W),rnd(0,H),.6,'80,240,180');if(n===4)for(let i=0;i<16;i++)spark(rnd(0,W),rnd(H*.15,H*.8),'255,230,110')}
 else if(world==='electricity'){if(n===1)bolt(1);if(n===2)for(let i=0;i<5;i++)bolt(1.4);if(n===3)for(let i=0;i<3;i++)bolt(.7);if(n===4)for(let i=0;i<30;i++)spark(W/2,H/2,'180,220,255')}
 else if(world==='hue'){if(n===1)items.push({kind:'orb',x:rnd(W*.2,W*.8),y:rnd(H*.2,H*.8),r:10,life:1,h:hue});if(n===2)hue=(hue+180)%360;if(n===3)for(let i=0;i<12;i++)items.push({kind:'orb',x:rnd(0,W),y:rnd(0,H),r:rnd(8,28),life:1,h:(hue+i*12)%360});if(n===4)for(let i=0;i<24;i++)spark(rnd(0,W),rnd(0,H),'255,255,255')}
}
for(let i=1;i<=4;i++){const el=document.getElementById(['blue','red','green','yellow'][i-1]);el.onpointerdown=()=>action(i,true);el.onpointerup=()=>action(i,false)}
const worlds=['bubbles','waves','electricity','hue','physics'];function nextWorld(){setWorld(worlds[(worlds.indexOf(world)+1)%worlds.length])}
function adjustKnob(d){control.knob=clamp(control.knob+d,0,100);updateDev()}
function adjustRoller(d){control.roller=clamp(control.roller+d,-100,100);updateDev()}
function setJoy(x,y){control.jx=clamp(x,-1,1);control.jy=clamp(y,-1,1);updateDev()}
addEventListener('keydown',e=>{if('1234'.includes(e.key))action(+e.key,true);if(e.key.toLowerCase()==='m')nextWorld();if(e.key.toLowerCase()==='a')adjustKnob(-5);if(e.key.toLowerCase()==='d')adjustKnob(5);if(e.key==='ArrowLeft')adjustRoller(-10);if(e.key==='ArrowRight')adjustRoller(10);if(e.key.toLowerCase()==='j')setJoy(control.jx-.2,control.jy);if(e.key.toLowerCase()==='l')setJoy(control.jx+.2,control.jy);if(e.key.toLowerCase()==='w')setJoy(control.jx,control.jy-.2);if(e.key.toLowerCase()==='s')setJoy(control.jx,control.jy+.2)});
addEventListener('keyup',e=>{if('1234'.includes(e.key))action(+e.key,false)});
function setWorld(w){if(!worlds.includes(w))w='bubbles';world=w;items=[];if(w==='physics'&&!balls.length)resetPhysics();document.getElementById('modeName').textContent=w.toUpperCase()+' WORLD';report()}
document.getElementById('modeButton').onclick=nextWorld;
function updateDev(){let kv=document.getElementById('knobValue'),rv=document.getElementById('rollerValue'),stick=document.getElementById('stick');if(kv)kv.textContent=Math.round(control.knob);if(rv)rv.textContent=Math.round(control.roller);if(stick)stick.style.transform=`translate(${control.jx*24}px,${control.jy*24}px)`}
document.getElementById('knobDown').onclick=()=>adjustKnob(-5);document.getElementById('knobUp').onclick=()=>adjustKnob(5);document.getElementById('rollerLeft').onclick=()=>adjustRoller(-10);document.getElementById('rollerRight').onclick=()=>adjustRoller(10);
function background(){if(world==='physics'){ctx.fillStyle='#090e1b';ctx.fillRect(0,0,W,H);if(quality==='HIGH'){ctx.strokeStyle='rgba(255,255,255,.045)';ctx.lineWidth=1;ctx.beginPath();for(let x=0;x<W;x+=96){ctx.moveTo(x,0);ctx.lineTo(x,H)}for(let y=0;y<H;y+=96){ctx.moveTo(0,y);ctx.lineTo(W,y)}ctx.stroke()}return}
 if(world==='bubbles'){let g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,'#020817');g.addColorStop(.45,'#062b49');g.addColorStop(1,'#031525');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);let count=quality==='HIGH'?8:4;for(let i=0;i<count;i++){let x=(i*173+t*18)%(W+240)-120,y=H*(.15+.1*(i%6));let rg=ctx.createRadialGradient(x,y,0,x,y,180);rg.addColorStop(0,'rgba(60,190,255,.08)');rg.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=rg;ctx.fillRect(x-180,y-180,360,360)}}
 else if(world==='waves'){let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#063b57');g.addColorStop(.55,'#07506a');g.addColorStop(1,'#021e32');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);let layers=quality==='HIGH'?3:2;for(let layer=0;layer<layers;layer++){ctx.strokeStyle=`rgba(${100+layer*35},${205+layer*12},255,${.08+.06*intensity})`;ctx.lineWidth=1+layer*.5;for(let y=15+layer*12;y<H;y+=55){ctx.beginPath();for(let x=0;x<=W;x+=24){let yy=y+Math.sin(x*.014+t*(1.2+layer*.3)+y*.018)*(8+layer*4)*intensity;x?ctx.lineTo(x,yy):ctx.moveTo(x,yy)}ctx.stroke()}}}
 else if(world==='electricity'){let g=ctx.createRadialGradient(W*.5,H*.45,0,W*.5,H*.45,Math.max(W,H)*.7);g.addColorStop(0,'#101a3b');g.addColorStop(.45,'#080c22');g.addColorStop(1,'#02030a');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<(quality==='HIGH'?45:25);i++){let x=(i*137)%W,y=(i*79+t*(6+i%5))%H;ctx.fillStyle='rgba(130,170,255,.12)';ctx.fillRect(x,y,1.5,1.5)}}
 else{hue=(hue+.08*speed)%360;let g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,`hsl(${hue},75%,28%)`);g.addColorStop(.5,`hsl(${(hue+65)%360},80%,42%)`);g.addColorStop(1,`hsl(${(hue+135)%360},72%,25%)`);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<(quality==='HIGH'?6:3);i++){let x=W*(.15+.14*i)+Math.sin(t*.35+i)*W*.08,y=H*(.25+.1*(i%4))+Math.cos(t*.28+i)*H*.12;let rg=ctx.createRadialGradient(x,y,0,x,y,Math.min(W,H)*.32);rg.addColorStop(0,`hsla(${(hue+i*35)%360},95%,70%,.16)`);rg.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=rg;ctx.fillRect(x-W*.3,y-H*.3,W*.6,H*.6)}}}
function stepPhysics(dt){const gx=control.jx*520+control.roller*1.8,gy=300+control.jy*520;for(const b of balls){b.vx+=gx*dt;b.vy+=gy*dt;b.vx*=.999;b.vy*=.999;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x<b.r){b.x=b.r;b.vx=Math.abs(b.vx)*.88}else if(b.x>W-b.r){b.x=W-b.r;b.vx=-Math.abs(b.vx)*.88}if(b.y<b.r){b.y=b.r;b.vy=Math.abs(b.vy)*.88}else if(b.y>H-b.r){b.y=H-b.r;b.vy=-Math.abs(b.vy)*.88}}
 for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++){let a=balls[i],b=balls[j],dx=b.x-a.x,dy=b.y-a.y,min=a.r+b.r,d2=dx*dx+dy*dy;if(d2>=min*min||d2<.0001)continue;let d=Math.sqrt(d2),nx=dx/d,ny=dy/d,over=min-d;a.x-=nx*over*.5;a.y-=ny*over*.5;b.x+=nx*over*.5;b.y+=ny*over*.5;let rvx=b.vx-a.vx,rvy=b.vy-a.vy,sep=rvx*nx+rvy*ny;if(sep<0){let ma=a.r*a.r,mb=b.r*b.r,imp=-(1+.9)*sep/(1/ma+1/mb);a.vx-=imp*nx/ma;a.vy-=imp*ny/ma;b.vx+=imp*nx/mb;b.vy+=imp*ny/mb}}}
function drawPhysics(){for(const b of balls){if(quality==='HIGH'){ctx.fillStyle='rgba(0,0,0,.18)';ctx.beginPath();ctx.ellipse(b.x+3,b.y+6,b.r*.82,b.r*.34,0,0,TAU);ctx.fill()}const s=ballSprite(b.c),d=b.r*2;ctx.drawImage(s,b.x-b.r,b.y-b.r,d,d)}}
function drawItem(o,i){if(o.kind==='bubble'){o.w+=.026*speed;o.age+=(1/30)*speed;let wind=control.roller*.011+control.jx*.9;o.vx+=(wind-o.vx*.055)*.016;o.x+=(o.vx*1.7+Math.sin(o.w+o.phase)*.38*o.depth)*speed;o.y+=(o.vy*2.15*o.rise-control.jy*.34)*speed;if(o.x<-o.r)o.x=W+o.r;if(o.x>W+o.r)o.x=-o.r;if(o.age>o.maxAge||o.y<-o.r){let x=o.x,y=Math.max(o.r,o.y),c=o.c;items.splice(i,1);bubbleBurst(x,y,c);return}const s=bubbleSprite(o.c),d=o.r*2;ctx.globalAlpha=clamp((.5+.5*intensity)*o.depth,.42,1);ctx.drawImage(s,o.x-o.r,o.y-o.r,d,d);ctx.globalAlpha=1}
 else if(o.kind==='popwave'){o.r+=18*speed;o.life-=.018*speed;let popped=[];for(let j=items.length-1;j>=0;j--){let b=items[j];if(b.kind==='bubble'&&Math.abs(Math.hypot(b.x-o.x,b.y-o.y)-o.r)<28+b.r*.45){popped.push(b);items.splice(j,1)}}for(const b of popped)bubbleBurst(b.x,b.y,'255,110,145');if(o.life<=0||o.r>Math.hypot(W,H)){let k=items.indexOf(o);if(k>=0)items.splice(k,1);return}ctx.strokeStyle='rgba(255,90,135,'+(o.life*.75)+')';ctx.lineWidth=6+o.life*10;ctx.beginPath();ctx.arc(o.x,o.y,o.r,0,TAU);ctx.stroke()}
 else if(o.kind==='mega'){o.r+=(o.target-o.r)*.045*speed;o.life-=.006*speed;let pulse=1+Math.sin(t*6)*.025,d=o.r*2*pulse,s=bubbleSprite(o.c);ctx.save();ctx.shadowBlur=quality==='HIGH'?28:12;ctx.shadowColor='rgba(255,210,60,.65)';ctx.globalAlpha=clamp(o.life+.15,.25,1);ctx.drawImage(s,o.x-d/2,o.y-d/2,d,d);ctx.restore();ctx.globalAlpha=1;if(o.life<=0){let x=o.x,y=o.y,r=o.r,k=items.indexOf(o);if(k>=0)items.splice(k,1);ripple(x,y,7,'255,215,70');for(let q=0;q<14;q++){let a=q/14*TAU,bx=x+Math.cos(a)*r*.55,by=y+Math.sin(a)*r*.55;bubble(bx,by,rnd(9,23),'255,205,70');let b=items[items.length-1];b.vx=Math.cos(a)*rnd(1.4,3.1);b.vy=Math.sin(a)*rnd(1.4,3.1)-.8}for(let q=0;q<30;q++)spark(x+rnd(-r*.35,r*.35),y+rnd(-r*.35,r*.35),'255,220,95');return}}
 else if(o.kind==='ripple'){o.r+=4.2*speed;o.life-=.008*speed;if(o.life<=0){items.splice(i,1);return}ctx.strokeStyle=`rgba(${o.c},${o.life*.45*intensity})`;ctx.lineWidth=1+o.p*2;ctx.beginPath();ctx.ellipse(o.x,o.y,o.r,o.r*.42,0,0,TAU);ctx.stroke()}
 else if(o.kind==='bolt'){o.life-=.045*speed;if(o.life<=0){items.splice(i,1);return}ctx.save();if(quality==='HIGH'){ctx.shadowBlur=10;ctx.shadowColor='rgba(120,180,255,.8)'}ctx.beginPath();o.pts.forEach((p,j)=>j?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.strokeStyle=`rgba(205,230,255,${o.life*intensity})`;ctx.lineWidth=1.5+o.power*2.5;ctx.stroke();ctx.restore()}
 else if(o.kind==='orb'){o.r+=2;o.life-=.012;if(o.life<=0){items.splice(i,1);return}let g=ctx.createRadialGradient(o.x,o.y,0,o.x,o.y,o.r*2);g.addColorStop(0,`hsla(${o.h},100%,80%,${o.life*.7})`);g.addColorStop(1,`hsla(${o.h},100%,50%,0)`);ctx.fillStyle=g;ctx.beginPath();ctx.arc(o.x,o.y,o.r*2,0,TAU);ctx.fill()}
 else{o.x+=o.vx*speed;o.y+=o.vy*speed;o.vx*=.985;o.vy*=.985;o.life-=.025*speed;if(o.life<=0){items.splice(i,1);return}ctx.globalAlpha=o.life;ctx.fillStyle=`rgb(${o.c})`;ctx.beginPath();ctx.arc(o.x,o.y,2.5,0,TAU);ctx.fill();ctx.globalAlpha=1}}
function report(){if(ws?.readyState===1)ws.send(JSON.stringify({type:'screen_state',version:'v0.9',world,fps:Math.round(fps),quality,balls:balls.length,items:items.length,physicsMs:+physicsMs.toFixed(1),renderMs:+renderMs.toFixed(1),frameMs:+frameMs.toFixed(1),maxFrameMs:+maxFrameMs.toFixed(1),lateFrames,controls:control}))}
function frame(now){requestAnimationFrame(frame);const rawFrameMs=now-lastFrame;frameMs=frameMs*.85+rawFrameMs*.15;maxFrameMs=Math.max(maxFrameMs,rawFrameMs);if(rawFrameMs>25)lateFrames++;let elapsed=Math.min(.066,rawFrameMs/1000);lastFrame=now;fpsFrames++;if(now-fpsClock>=1000){fps=fpsFrames*1000/(now-fpsClock);fpsFrames=0;fpsClock=now;if(fps<25)quality='LOW';else if(fps>28)quality='HIGH';if(now-lastReport>1000){report();lastReport=now;maxFrameMs=0;lateFrames=0}}t+=elapsed*speed;if(world==='bubbles'){if(held.has('BLUE')&&Math.random()<Math.min(1,elapsed*16)){let a=rnd(-1.02,-.55),v=rnd(1.5,3.2);bubble(W/2+rnd(-45,45),H+25,rnd(10,25)+control.knob*.12,'55,175,255');let b=items[items.length-1];b.vx=Math.cos(a)*v*1.55;b.vy=Math.sin(a)*v*1.55}if(held.has('GREEN')&&Math.random()<Math.min(1,elapsed*24)){bubble(rnd(W*.08,W*.92),H+20,rnd(6,16),'45,235,165')}}let p0=performance.now();if(world==='physics'){physicsAcc+=elapsed;const step=1/30;let loops=0;while(physicsAcc>=step&&loops<2){stepPhysics(step);physicsAcc-=step;loops++}}physicsMs=physicsMs*.85+(performance.now()-p0)*.15;let r0=performance.now();background();if(world==='physics')drawPhysics();else{if(world==='bubbles'&&items.filter(x=>x.kind==='bubble').length<22){let base=12+control.knob*.22;bubble(rnd(0,W),H+30,rnd(base*.65,base*1.35),Math.random()<.25?'90,225,205':'70,175,255')}if(world==='electricity'&&Math.random()<.008*intensity)bolt(.45);if(world==='hue'&&Math.random()<.015*intensity&&items.length<80)items.push({kind:'orb',x:rnd(0,W),y:rnd(0,H),r:5,life:.7,h:(hue+rnd(-50,50)+360)%360});for(let i=items.length-1;i>=0;i--)drawItem(items[i],i)}renderMs=renderMs*.85+(performance.now()-r0)*.15}
function remoteInput(event){const m={BLUE_DOWN:1,RED_DOWN:2,GREEN_DOWN:3,YELLOW_DOWN:4,BLUE_UP:1,RED_UP:2,GREEN_UP:3,YELLOW_UP:4};if(m[event])action(m[event],event.endsWith('_DOWN'))}
function applyControl(c){if(c.knob!=null)control.knob=clamp(+c.knob,0,100);if(c.roller!=null)control.roller=clamp(+c.roller,-100,100);if(c.jx!=null)control.jx=clamp(+c.jx,-1,1);if(c.jy!=null)control.jy=clamp(+c.jy,-1,1);updateDev()}
function connect(){ws=new WebSocket(`ws://${location.host}/ws?role=display`);ws.onopen=report;ws.onclose=()=>setTimeout(connect,1500);ws.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m.type==='command'&&m.command==='reload'){window.location.replace('/index.html?reload='+Date.now());return}if(m.type==='input'&&m.event)remoteInput(m.event);if(m.type==='control'&&m.control)applyControl(m.control);if((m.type==='state'||m.type==='hello')&&m.state){let s=m.state;if(s.world&&s.world!==world)setWorld(s.world);intensity=(s.intensity??70)/100;speed=(s.speed??100)/100;document.getElementById('controls').style.display=s.showControls===false?'none':'flex'}}}
connect();updateDev();background();requestAnimationFrame(frame);