const canvas=document.getElementById('world'),ctx=canvas.getContext('2d');let W,H,dpr,world='bubbles',t=0,items=[],ws,intensity=.7,speed=1;
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function bubble(x=Math.random()*W,y=H*.8,r=12+Math.random()*35,c='80,170,255'){items.push({kind:'bubble',x,y,r,vx:(Math.random()-.5)*1.2,vy:-.3-Math.random(),c})}
function ripple(x=W/2,y=H/2,p=1,c='80,180,255'){items.push({kind:'ripple',x,y,r:5,p,life:1,c})}
function bolt(){let pts=[],tx=W/2+(Math.random()-.5)*W*.5;for(let i=0;i<20;i++){let q=i/19;pts.push({x:W/2+(tx-W/2)*q+(Math.random()-.5)*60*(1-q),y:q*H*.75})}items.push({kind:'bolt',pts,life:1})}
function action(n,down=true){if(!down)return;if(world==='bubbles'){if(n===1)bubble();if(n===2)ripple(W/2,H/2,2,'255,70,90');if(n===3)for(let i=0;i<5;i++)bubble(W/2+(Math.random()-.5)*120,H-80,10+Math.random()*18,'40,230,130');if(n===4)for(let i=0;i<5;i++)bubble(W/2+(Math.random()-.5)*200,H*.5,8+Math.random()*15,'255,215,60')}else if(world==='waves'){if(n===1)ripple(Math.random()*W,Math.random()*H*.8);if(n===2)ripple(W/2,H/2,3,'255,70,90');if(n===3)for(let i=0;i<8;i++)ripple(Math.random()*W,Math.random()*H,.5,'60,230,150');if(n===4)for(let i=0;i<8;i++)ripple(Math.random()*W,Math.random()*H,.7,'255,220,70')}else{if(n===1)bolt();if(n===2)for(let i=0;i<4;i++)bolt();if(n===3)for(let i=0;i<2;i++)bolt();if(n===4)for(let i=0;i<25;i++)items.push({kind:'spark',x:W/2,y:H/2,vx:(Math.random()-.5)*8,vy:(Math.random()-.5)*8,life:1})}}
for(let i=1;i<=4;i++){const el=document.getElementById(['blue','red','green','yellow'][i-1]);el.onpointerdown=()=>action(i)}
addEventListener('keydown',e=>{if('1234'.includes(e.key))action(+e.key);if(e.key.toLowerCase()==='m')setWorld(world==='bubbles'?'waves':world==='waves'?'electricity':'bubbles')});
function setWorld(w){world=w;items=[];document.getElementById('modeName').textContent=w.toUpperCase()+' WORLD';report()}
document.getElementById('modeButton').onclick=()=>setWorld(world==='bubbles'?'waves':world==='waves'?'electricity':'bubbles');
function draw(){t+=.016*speed;if(world==='bubbles'){let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#020617');g.addColorStop(1,'#042038');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);if(items.filter(x=>x.kind==='bubble').length<12)bubble(Math.random()*W,H+30)}else if(world==='waves'){ctx.fillStyle='#052b40';ctx.fillRect(0,0,W,H);ctx.strokeStyle=`rgba(100,210,255,${.08+.12*intensity})`;for(let y=20;y<H;y+=35){ctx.beginPath();for(let x=0;x<W;x+=15){let yy=y+Math.sin(x*.018+t*2+y*.02)*10*intensity;x?ctx.lineTo(x,yy):ctx.moveTo(x,yy)}ctx.stroke()}}else{ctx.fillStyle='#050713';ctx.fillRect(0,0,W,H)}
for(let i=items.length-1;i>=0;i--){let o=items[i];if(o.kind==='bubble'){o.x+=o.vx*speed;o.y+=o.vy*speed;if(o.y<-o.r){items.splice(i,1);continue}let g=ctx.createRadialGradient(o.x-o.r*.3,o.y-o.r*.3,2,o.x,o.y,o.r);g.addColorStop(0,'rgba(255,255,255,.9)');g.addColorStop(.2,`rgba(${o.c},${.35+.5*intensity})`);g.addColorStop(1,`rgba(${o.c},.05)`);ctx.fillStyle=g;ctx.beginPath();ctx.arc(o.x,o.y,o.r,0,Math.PI*2);ctx.fill()}else if(o.kind==='ripple'){o.r+=4*speed;o.life-=.008*speed;if(o.life<=0){items.splice(i,1);continue}ctx.strokeStyle=`rgba(${o.c},${o.life*.6*intensity})`;ctx.lineWidth=1+o.p*2;ctx.beginPath();ctx.ellipse(o.x,o.y,o.r,o.r*.45,0,0,Math.PI*2);ctx.stroke()}else if(o.kind==='bolt'){o.life-=.05*speed;if(o.life<=0){items.splice(i,1);continue}ctx.beginPath();o.pts.forEach((p,j)=>j?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.strokeStyle=`rgba(220,240,255,${o.life*intensity})`;ctx.lineWidth=2+3*intensity;ctx.stroke()}else{ o.x+=o.vx;o.y+=o.vy;o.life-=.03;if(o.life<=0){items.splice(i,1);continue}ctx.globalAlpha=o.life;ctx.fillStyle='#ffe080';ctx.fillRect(o.x,o.y,3,3);ctx.globalAlpha=1}}
requestAnimationFrame(draw)}
function remoteInput(event){
 const m={BLUE_DOWN:1,RED_DOWN:2,GREEN_DOWN:3,YELLOW_DOWN:4};
 if(m[event]) action(m[event],true);
 // *_UP events are intentionally accepted now so hold behaviours can use them later.
}
function connect(){ws=new WebSocket(`ws://${location.host}/ws?role=display`);ws.onopen=report;ws.onclose=()=>setTimeout(connect,1500);ws.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m.type==='command'&&m.command==='reload'){
    window.location.replace('/index.html?reload=' + Date.now());
    return;
}if(m.type==='input'&&m.event)remoteInput(m.event);if((m.type==='state'||m.type==='hello')&&m.state){let s=m.state;if(s.world&&s.world!==world)setWorld(s.world);intensity=(s.intensity??70)/100;speed=(s.speed??100)/100;document.getElementById('controls').style.display=s.showControls===false?'none':'flex'}}}function report(){if(ws?.readyState===1)ws.send(JSON.stringify({type:'screen_state',version:'v0.6',world}))}connect();draw();
